######################################################################
# @author      : joe (joe@joe-Aspire-E1-531G)
# @file        : makefile
# @created     : 週日  4月 24, 2022 14:40:00 CST
######################################################################

# This flag is to control to use release or debug mode to compile code files.
debug ?= 0

.PHONY: all 

# Compile all files in the directory "exmaple"
all:
	cd ./testObserverPattern; $(MAKE) debug=$(debug)

